spiceai/datafusion-federation

Cargo.toml, datafusion-federation/src/table_provider.rs
Fixes the fallback to `supports_filters_pushdown` for table providers in FederatedTableProviderAdaptor
=> Fix the fallback to the table provider for supports_filters_pushdown

sources/sql/src/lib.rs
Also adds support for all expression types, and rewrites the column identifiers where appropriate.
Closes https://github.com/spiceai/spiceai/issues/1508
A fairly large PR that rewrites the expressions to replace the table relation identifiers with the remote table.
i.e. take this query to DataFusion: `SELECT df_table.id, df_table.name FROM df_table`
If the name in the remote engine was `remote_table` then the query that we would try to send to the remote table would be `SELECT df_table.id, df_table.name FROM remote_table` - which is incorrect.
Previously, I tried to compensate for this by adding a Subquery alias, which would rename the remote table back to the DataFusion table so that the existing references would work, i.e.:
`SELECT df_table.id, df_table.name FROM remote_table AS …
=> Fix the table scan rewrite to properly rewrite column relations

sources/sql/Cargo.toml, sources/sql/src/lib.rs
Handles rewrites for aggregates like `MAX` which have a column name that embeds the table name.
=> Handle table rewrites for aggregation functions

sources/flight-sql/src/executor/mod.rs, sources/sql/src/connectorx/executor.rs, sources/sql/src/executor.rs, sources/sql/src/lib.rs
Use the Unparser Dialect from the `unparser` module in DataFusion instead of using it from the `sqlparser-rs` project directly. Then we can call `unparser.plan_to_sql` which will generate SQL based on the Dialect we want, instead of it being generated using the Default dialect.
=> Use Unparser Dialect for plan_to_sql

Cargo.toml, datafusion-federation/Cargo.toml, datafusion-federation/src/lib.rs, datafusion-federation/src/schema_cast.rs, datafusion-federation/src/schema_cast/record_convert.rs, sources/sql/src/lib.rs
Handles the case where the schema returned from the federated source does not exactly match the schema DataFusion expects.
I've observed this happen when running this query:
```sql
SELECT count(1) FROM remote_table
```
DataFusion during its planning expects this is an Int64, but the remote source returned an Int32. This caused issues when decoding record batches based on the Int64 schema, since the number of bytes was incorrect.
=> Add layer to convert actual schema to expected schema

sources/sql/Cargo.toml, sources/sql/src/lib.rs
Fixes https://github.com/spiceai/spiceai/issues/1581
Improve expressions logic re-write to correctly handle cases where 
1. part of expression matches table name, for example
```sql
SELECT app_table_a FROM (SELECT a as app_table_a FROM app_table)
```
`app_table_a` contains `app_table` but it should not be rewritten.
Note: I've tried to see if there is something we can use to make this more robust (TableReference, relationship, etc), but found no difference when column belongs to one of registered tables or just other name/alias
2. expression contains multiple instances of the same table or multiple different tables
=> Improve rewrite logic for expressions

datafusion-federation/src/analyzer.rs, sources/sql/src/lib.rs
This fixes two things:
- a missing qualifier when wrap_projection, which will cause ambiguous selecting when join two tables as they contain same column name
- change the logic of how we handle the convention between df table to source table. Instead of mutating the plan during planning that could confuse df entire logic plan tree, this will create a query-only plan with all necessary rewrites when executing.
after this, inner join starts working
```
sql> explain  select * from fed inner join acc on acc.email = fed.email;
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Remove table reference mutating during logical planning, converting query when executing

sources/sql/src/lib.rs
When col.relation is there, means the column has been already taken care of. It doesn't need to be overwritten again.
This addresses tpc-9 query failure.
=> do not over eager rewrite column when col relation is there

datafusion-federation/src/plan_node.rs
Changes the visibility of `FederatedPlanner` to public to allow custom QueryPlanners to include it along with other extension planners.
=> Make the `FederatedPlanner` public for use in custom query planners

datafusion-federation/src/schema_cast.rs
[EnforceDistribution PhisicalOptimizerRule](https://github.com/apache/datafusion/blob/9df957b63ea4c9fb787c6f9a3c15d1dcd394ac72/datafusion/core/src/physical_optimizer/enforce_distribution.rs#L189) aggressively enforces inputs to be split and processed in parallel which leads to re-ordering of record batches containing few records.
`benefits_from_input_partitioning` setting enforces 1-1 relationship between `SchemaCastScanExec` and its input preventing re-ordering. This does not block partitioning/parallel processing in general, just ensures 1-1 mapping for SchemaCastScanExec and wrapped input.
Example plan. `RepartitionExec` is automatically enforced by the optimization. Order of resultant records batches vary as query records are processed in parallel.
```console …
```
=> Preserve records batch order when SchemaCastScanExec is involved

Cargo.toml, sources/sql/src/lib.rs
Support for rewriting plans with UNNEST. `test_rewrite_table_scans_unnest`  contains example queries.
Note: PR includes patch for `datafusion` crate which is required to unparse rewritten plan 
Closes https://github.com/spiceai/spiceai/issues/3068
=> Support for rewriting plans with UNNEST

datafusion-federation/src/analyzer.rs
Improve `FederationAnalyzerRule` to correctly handle Unnest LP.
Unnest returns columns to unnest as `expressions` but does not support passing them back to `with_new_exprs` - see `assert_no_expressions `. Instead, it uses data from its internal representation.
```rust
LogicalPlan::Unnest(Unnest {
exec_columns: columns,
options,
..
}) => {
self.assert_no_expressions(expr)?;
let input = self.only_input(inputs)?;
// Update schema with unnested column type.
let new_plan =
unnest_with_options(input, columns.clone(), options.clone())?;
Ok(new_plan)
}
```
=> Correctly handle unnest by FederationAnalyzerRule

Cargo.toml, datafusion-federation/src/analyzer.rs, datafusion-federation/src/optimize.rs
Add logic to run the `optimize_projections` rule as part of federated plan optimization to push down projections and prune unused columns from the request.
Draft while pending https://github.com/spiceai/datafusion/pull/55 PR
=> Run `optimize_projections` as part of federated plan optimization

datafusion-federation/src/optimize.rs, datafusion-federation/src/optimize/optimize_projections/mod.rs, datafusion-federation/src/optimize/optimize_projections/required_indices.rs
PR introduces a modified version of DataFusion's [`OptimizeProjections`](https://github.com/apache/datafusion/blob/main/datafusion/optimizer/src/optimize_projections/mod.rs) rule, updated to allow the DataFusion unparser to correctly convert the optimized plan to SQL. It also maintains a simple and readable query layout.
See [DataFusion discussion](https://github.com/apache/datafusion/pull/13267) for more details on motivation to create own modified version of the rule instead of modifying the original one (DF).
=> Add own modified version of Datafusion `optimize_projections` rule

sources/sql/src/lib.rs
When attempting to rewrite a query like `select call_center from (select cc_call_center_id Call_Center from call_center order by cc_call_center_id limit 100);`, where `call_center` table is rewritten to source `source_schema.call_center`, the rewrite mechanism would wrongly rewrite the **column** subquery alias `call_center` using **table** rewrite, making the `select call_center` a `select source_schema.call_center`, which is incorrect.
This PR fix the issue.
Also added a unit test, which would fail without the fix
- https://github.com/spiceai/spiceai/issues/4009
=> fix: rewrite shouldn't be performed on a column name same as the table name

sources/sql/src/lib.rs
Datafusion has a bug in preserving logical plan expressions for `LogicalPlan::Limit` when calling `plan.with_new_expressions()`.
To fix this during `rewrite_table_scans` we'll need to preserve initial fetch and limit
Need to fix in datafusion itself, but it is not trivial. I will rise an issue for that.
=> fix: handle `LogicalPlan::Limit` separately to preserve skip and offset in `rewrite_table_scans`

sources/sql/src/rewrite/plan.rs
When rewritting the expressions, the filter expressions within the table scan were ignored previously. This PR fixes the issue by rewritting Filter expressions within the tablescan.
- https://github.com/spiceai/spiceai/issues/4077
=> fix: filter expressions within the tablescan should also be rewritten

sources/sql/src/rewrite/plan.rs
Fix the logic for column expression rewrite when table name same as column name. Also added a test case to ensure the validity of the change.
- https://github.com/spiceai/spiceai/issues/4136
=> fix: column expression rewrite

sources/sql/src/rewrite/plan.rs
Attempt number 2 at fixing the bug, original PR was #38. Attached is the context from that PR.
The missing piece was that I needed to add a pass to collect any subquery table scans from expressions, since they were being collecting during the original logic and I broke it when I only considered the table scans from the logical plan nodes.
An OuterReferenceColumn (aka correlated subquery) is a column in a subquery that references a column from the parent query.
Consider the following query:
```sql
SELECT employee_name,
(SELECT AVG(salary)
FROM salaries s2
WHERE s2.department = e.department) as dept_avg_salary
FROM employees e;
```
In this query, `e.department` in the subquery refers to the department from the outer query's `employees` table. For each employee in the outer query, the …
=> feat: fix OuterReferenceColumns not being rewritten correctly (take 2)

sources/sql/src/lib.rs, sources/sql/src/rewrite/ast.rs
Fixes an issue where a subquery that was wrapped in a sqlparser::ast::Expr::Nested was not properly being rewritten. I've added support for all of the remaining ast expressions, even ones that aren't likely to be generated by the DataFusion Unparser, just to ensure we have full coverage. I've also added several tests to validate the new changes, including the test case that was failing previously.
=> feat: add support for more AST expressions for multi-level rewrites

sources/sql/src/rewrite/plan.rs
Correctly federate the `LogicalPlan::Join`. handle the on expression, which represent the Equijoin clause (e.g. ON a = b) in the Vec<(Expr, Expr)> format. When directly read from plan.exprs(), the Equijoin clause is readed as separate exprs Expr(Col(a)) Expr(Col(b)), instead of a Expr(Binary) of a = b, which causes error in https://github.com/apache/datafusion/blob/39063f6ccc403a6d0c8dd171318c5f201d516636/datafusion/expr/src/logical_plan/plan.rs#L924 and fail to federate the plan.
Note that the intersect / except sql query is parsed as logical plans with left semi / anti join with Equijoin clause represented in Join.on, whereas common join query have condition represented in Join.filter.
- https://github.com/spiceai/spiceai/issues/5948
- https://github.com/spiceai/spiceai/issues/5941
=> fix: join rewrite can handle the Equijoin clause
